# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/arxiv-downloader',
                'doc_host': 'https://0xSynth.github.io',
                'git_url': 'https://github.com/0xSynth/arxiv-downloader',
                'lib_path': 'arxiv_downloader'},
  'syms': {'arxiv_downloader.core': {'arxiv_downloader.core.foo': ('core.html#foo', 'arxiv_downloader/core.py')}}}
